
# Setup and Helper Functions
```{r}
setwd("C:/Users/Administrator/Desktop/CatherPath")
#setwd("C:/Users/zxio506/Desktop/CatherPath")

# load packages
rm(list=ls())
library("R.matlab")
library("alphashape3d")

# loads data from text file to dataframe
txt2df = function(txt,from,to,bool_byrow,n_ncol) {
  
  txt = gsub("\\s+"," ",txt[from:to]) # remove space
  txt = gsub("^\\s+|\\s+$","",txt)    # remove leading/trailing space
  txt = gsub("\\( |\\)","",txt)       # remove brackets if exist
  
  df = data.frame(matrix(as.numeric(unlist(strsplit(txt," "))), byrow=bool_byrow, ncol=n_ncol))
  
  return(df)
  
}

# function to load Ensite generated points, converted to mesh, and catheter path recording
read_data_beijing = function(f3,f5) {
  
  # helper function to find the values of landmark given string
  find_landmark = function(txt,s) {
    
    txt = txt[grep(s,txt)[1] + 1]
    txt = gsub("^\\s+|\\s+$","",gsub("\\s+"," ",txt)) # remove all additional spaces
    
    vals = as.numeric(strsplit(txt," ")[[1]])
    
    return(vals)
    
  }

  # load third data
  t3      = readLines(f3)
  d3_vert = txt2df(t3 ,grep("<Vertices",t3)[1] + 1 ,grep("</Vertices>",t3)[1] - 1 ,TRUE ,3)

  d3_land = data.frame(LSPV = find_landmark(t3,"<Label name=\"LSPV\">"),
                       LIPV = find_landmark(t3,"<Label name=\"LIPV\">"),
                       LAA  = find_landmark(t3,"<Label name=\"LAA\">"),
                       RSPV = find_landmark(t3,"<Label name=\"RSPV\">"),
                       RIPV = find_landmark(t3,"<Label name=\"RIPV\">"))

  # load fifth data
  t5     = readLines(f5)
  d5_geo = txt2df(t5 ,grep("Number of geo",t5)[1] + 2   ,grep("EOF",t5)[1] - 1   ,TRUE ,3)
  
  # compute distance for each point in fifth data to third data
  d5_geo$dist = sapply(1:nrow(d5_geo),function(i)
       min(((d5_geo$X1[i] - d3_vert$X1)^2 + (d5_geo$X2[i] - d3_vert$X2)^2 + (d5_geo$X3[i] - d3_vert$X3)^2)^0.5))
  
  return(list(d3_vert,d3_land,d5_geo))
  
}
```

# Patient Data
  - d3 is the most complete and dense mesh
  - d5 catheter path

```{r}
# beijing Data patient files
beijing_patients = c("BaoZhongzhi",   # 1
                     "GaoXing",       # 2
                     "JiangTongjie",  # 3
                     "LiWenhai",      # 4
                     "ShenPinsheng",  # 5
                     "XinhuaWang",    # 6
                     "ZhangNengqin",  # 7
                     "ZhangWuhui",    # 8
                     "ZhenLixing",    # 9
                     "ZhiJianyou")    # 10

for (n_read in 1:length(beijing_patients)) {
  
  # create paths
  patient = beijing_patients[n_read]
  p_files = paste0(patient,"/",list.files(patient))
    
  # read files
  out = read_data_beijing(f3=p_files[grepl("3_GeoGrps",p_files)],f5=p_files[grepl("5_GeoPts", p_files)])

  # convert to positive unit coordinate system
  min_val = min(min(out[[1]]),min(out[[3]]))
  
  coords      = as.matrix(out[[1]] - min_val + 1)
  path_coords = as.matrix(out[[3]] - min_val + 1)
  PV_coords   = out[[2]] - min_val + 1
  
  # iterate through and apply concave hull 3 times
  new_coords = round(coords,0)
  for (iter in 1:2) {
    
    print(paste0(n_read," - ",iter))
    
    # compute concave hull of data
    ashape = ashape3d(new_coords, alpha = 3, pert = TRUE) # plot(ashape)
    
    if (iter == 1) { # save the first round of ashape
      ashape_vert = ashape$x
      ashape_tri  = ashape$triang[,c(1:3,9)]
      ashape_tri  = ashape_tri[ashape_tri[,4]>=2,1:3]
    }
    
    # convert concave hull mesh to pixel in an image volume
    ashape_edge = ashape$edge[ashape$edge[,8]>=2,1:2]
    vertices    = ashape$x
    
    new_coords = c()
    for (i in 1:nrow(ashape_edge)) {
      
      # define start and end point
      e1 = vertices[ashape_edge[i,1],]
      e2 = vertices[ashape_edge[i,2],]
      n_points = max(abs(e1 - e2))+1
      
      # interpolate through the line
      step = sapply(1:3,function(n) seq(e1[n],e2[n],length=n_points))
      
      # save the interpolated points as the new vertices of the concave hull
      new_coords = rbind(new_coords,step)
      
    }
    
  }
  
  # save raw data to file
  writeMat(paste0(patient,"/",patient,".mat")
           ,coord      = coords              # Vertices produced (3D point cloud mesh) by EnSite Software
           ,landmark   = PV_coords           # location of landmarks
           ,path       = path_coords[,1:3]   # Path of catheter recorded
           ,pathdist   = path_coords[,4]     # Distance of catheter path compared to mesh
           
           ,ashape_x   = ashape_vert # vertices of the concave hull computed
           ,ashape_tri = ashape_tri  # triangles of the mesh representing the concave hull
           ,mask_coord = new_coords  # coordinates of the rasterized mesh
  )
  
}
```
